### ISSUE TITLE
ATC parse error

### ISSUE THREAD

**Issue by micheldumontier** [bio-ontology-research-group/aberowl-orepo#92] opened 2015-10-17 22:32 UTC
BioPortal's version of ATC - http://bioportal.bioontology.org/ontologies/ATC has a reasonable hierachical rendering (minus a few classes) - http://bioportal.bioontology.org/ontologies/ATC?p=classes

which isn't at all the case for aberowl

http://aber-owl.net/ontology/ATC

**Comment by leechuck** [comment] 2015-10-18 07:59
The problem is that BioPortal serves an RDF version of ATC, not an OWL version. It's based on SKOS, and we need to add a SKOS renderer. More or less a duplicate of #88.

**Closed as completed by leechuck** 2015-10-18 07:59 UTC
Labels: duplicate
